### PR TITLE
armv7 support

### PR DESCRIPTION
**Pull request by fabricedesre**

### CODE REVIEW

**Comment by SimonSapin** [comment]
Could you instead rewrite these dependencies section to the newer more generic syntax? Things like `[target.'cfg(windows)'.dependencies]`

http://doc.crates.io/manifest.html#the-dependencies-section
https://doc.rust-lang.org/reference.html#conditional-compilation

Thanks!

**Comment by fabricedesre** [comment]
@SimonSapin I could only test locally on linux, and I don't see any test infra here.

**Comment by fabricedesre** [comment]
Let me change the unix by target_os=linux first...

**Comment by SimonSapin** [comment]
Looks good to me, but I don’t have write access to this repository.

**Comment by fabricedesre** [comment]
ping r? @aweinstock314

**Pull request merged**
